---
title: "Long-beaked common dolphin stranding along San Diego"
output: html_notebook
---

This is an attempt to model the number of stranded *Delphinus capensis* (*Dc*) along the San Diego county beaches. The question is if the number of *Dc* strandings per km (stranding rate) along the Silver Strand beach (SS) is greater than other areas in San Diego county. And if so, when did it happen in the last 20 years (2000-2019). Simple calculations of stranding rate revealed that the observed stranding rates of *Dc* along SS are often higher than those from other areas in San Diego county, with some exceptional years in the past (maybe add a figure here). In this analysis, I estimate the additional mortality that attributes to the observed increase in *Dc* strandings along SS.

N0 for capensis: 8,174 CV = 32% for Santa Catalina Basin. Jefferson et al. 2014 (Jefferson TA, Smultea MA, Bacon CE. 2014. Southern California Bight marine mammal density and abundance from aerial surveys, 2008-2013. Journal of Marine Animals and Their Ecology. 7: 14-30.)

To simplify the modeling process, I make the following assumptions.

1.  Carcass deposition probability (probability that a carcass is washed up onshore) is the same for SS as other areas in San Diego county. 
2.  Carcass deposition and detection probabilities (collectively $f$, i.e., probability of a carcass depositing on a beach and being detected and reported to the stranding response team) are the same over time and among all beaches in San Diego county.
3.  Instantaneous natural mortality rate $\mu_0$ and anthropogenic mortality rates $h$ are the same for all *Dc*s in the area and remained constant over time. These two are combined in the analysis ($\mu = \mu_0 + h$) and remain constant over time. Furthermore, I assume that the birth rate ($b$) remains constant and is combined with the mortality rates ($r = b - (\mu_0 + h)$).
4.  Additional mortality along SS in year $t$ ($\mu_{1,t}$) is time-dependent. ($\mu_{1,t}$ $\ge$ 0).
5.  No additional mortality existed prior to 2000.
6.  Abundance of *Dc* in 1999 was unknown but it was estimated to be 8174 (CV = 32%) in 2013 (Jefferson et al. 2014).

The number of strandings along the San Diego county in year t ($D_t$) is divided into two parts (SS and areas outside of SS): 

$D_t = D_{SS,t} + D_{\bar{SS},t}$

$D_{SS,t} = \int_0^1 N_t P_{SS} (\mu + \mu_1)f dt$,

where $P_{SS}$ is the probability that a *Dc* is along SS. I fix this to the proportion of the length of SS (X km) relative to the entire coast line of the San Diego county (Y km; $P_{SS} = X/Y = Z$).

$N_t = N_0 e^{(r - \mu_1)t}$

We do not have an abundance estimate for 1999. However, we have an estimate for 2013 so we use it to estimate $N_{1999}$ as part of the modeling process. 

For the areas outside of SS, 

$D_{\bar{SS},t} = \int_0^1 N_t (1 - P_{SS}) \mu f dt$,

We assume that the observed $D_{SS,t}$ and $D_{\bar{SS},t}$ are distributed as either Poisson or negative binomial distribution with the mean equals to the above equations.

In this model, unknowns are abundance ($N_t$, except $N_{1999}$), mortality rates ($\mu$ and $\mu_{1,t}$), and the birth rate ($b = r + \mu$), which are inferred from the observed numbers of *Dc* carcasses.

```{r setup}
rm(list=ls())
library(jagsUI)
library(tidyverse)
library(ggplot2)
library(bayesplot)

# load data on capensis strandings
capensis.data <- read.csv(file = "data/capensis_strandings.csv")

# coast line lengths
SD.coast.length <- 150403.3/1000 # meters from cetacean_v1.Rmd (SD.coast.no.MB.SDB.length)
SS.length <- 22135.74/1000  # meters from cetacean_v1.Rmd (SS.length)

D1 <- as.vector(capensis.data$n.SS)
D1[is.na(D1)] <- 0

D2 <- as.vector(capensis.data$n.noSS)

N <- c(rep(NA, 13), 8174, rep(NA, 7))

jags.data <- list(D1 = c(0, D1),
                  D2 = c(0, D2),
                  N = N,
                  P1 = SS.length/SD.coast.length,
                  T = (length(D1) + 1))

parameters.list <- c("r", "f", "mu", "mu1", "sigma_N", "N")

MCMC.params <- list(n.samples = 100000,
                    n.burnin = 75000,
                    n.thin = 5,
                    n.chains = 5)

jm.1 <- jags(data = jags.data,
             #inits = inits,
             parameters.to.save= parameters.list,
             model.file = "models/model_DcStranding_v1.txt",
             n.chains = MCMC.params$n.chains,
             n.burnin = MCMC.params$n.burnin,
             n.thin = MCMC.params$n.thin,
             n.iter = MCMC.params$n.samples,
             DIC = T, 
             parallel=T)

```


